import streamlit as st
import pandas as pd
import random
import base64

# == Paste your dataset here ========
dataset = [
    {
                "Feature / Capability": "AI/ML powered antimalware detection",
                "Description": "Uses AI and ML to detect malware",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "✅",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Real-time IOA detection, alerting, and mitigation",
                "Description": "Detects suspicious behaviors or Indicators of Attack in real time",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "⚠",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Root cause analysis via process tree",
                "Description": "Visualizes/analyzes attack origination and spread",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "⚠️",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "⚠️",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "⚠️",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "⚠️",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "On-execute process scan",
                "Description": "Scans files at moment of execution",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "✅",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "On-write scan",
                "Description": "Scans files when created or modified",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "✅",
                "SentinelOne": "⚠",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Auto incident grouping of alerts",
                "Description": "Automatically groups related alerts",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "⚠️",
                "CyclancePROTECT": "✅",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "⚠️",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "⚠️",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Single click threat mitigation and cleanup",
                "Description": "Enables rapid threat response and cleanup",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "⚠",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Network quarantine/isolation",
                "Description": "Isolates infected systems from network",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "⚠️",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Recovery of infected files",
                "Description": "Recovers files damaged or encrypted by malware",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "⚠️",
                "ESET Protect": "✅",
                "CrowdStrike": "⚠️",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "⚠️",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Continuous behaviour monitoring",
                "Description": "Constant surveillance for threats and attacks",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "⚠️",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "✅",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Exclusion (Allow/Block) list from detection",
                "Description": "Allows specific files/processes to be excluded or included",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "✅",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Zero day ransomware detection",
                "Description": "Detects previously unknown ransomware attacks",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "⚠",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Machine learning-powered anomaly detection",
                "Description": "Detects abnormal system or user activity using ML",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "⚠",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Single click file recovery",
                "Description": "Quickly restores files to pre-attack states",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "❌",
                "CyclancePROTECT": "❌",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "⚠️ (ransomware rollback only)",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅ (host restore suggestions)",
                "Symantec Endpoint Security": "✅",
                "Trellix": "⚠️",
                "ESET Protect": "✅",
                "CrowdStrike": "⚠️",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "⚠️",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Offline protection",
                "Description": "Endpoint protection when offline",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "✅",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Zero definition updates",
                "Description": "Detection without relying on signature/definition updates",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Signature Clone detection",
                "Description": "Detects threats via similarity to known malware signatures",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "❌",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "❌",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "DLL scan",
                "Description": "Scans dynamic link libraries for threats",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Autonomous threat detection and cleanup",
                "Description": "Automatic detection and removal with minimal user action",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "⚠",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Automatic definition updates",
                "Description": "Auto-updates threat signatures",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "✅",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Signature and signature-less detection",
                "Description": "Supports both traditional signatures and heuristic/behavioral methods",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "⚠",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "File-less attack detection",
                "Description": "Detects attacks not relying on files",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "System restoration",
                "Description": "Restores system after attack",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "❌",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "⚠️ (rollback in higher tiers)",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "⚠️",
                "ESET Protect": "✅",
                "CrowdStrike": "⚠️",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "⚠️",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "⚠️"
            },
            {
                "Feature / Capability": "Process termination",
                "Description": "Ends malicious or suspicious processes",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "✅",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "✅",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Forensic analysis",
                "Description": "Tools and logs for incident investigation",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "⚠️",
                "CyclancePROTECT": "❌",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "⚠️ (limited EDR Extra Strength)",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅ (forensics add-on)",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅ (EDRF with forensics)",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "⚠️",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Attack/Incident visualization",
                "Description": "Graphical/timeline representation of incidents",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "⚠️",
                "CyclancePROTECT": "❌",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "⚠️",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅ (Helix Connect visualization)",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "⚠️",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Vulnerability detection",
                "Description": "Identifies & remediates vulnerabilities via patch management",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "⚠️",
                "Bitdefender AV / GravityZone": "⚠️",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "⚠️ (add-on)",
                "McAfee ENS + ePO": "⚠️ (ePO Patch Mgmt)",
                "Palo Alto Cortex XDR": "⚠️ (Unpatched Vulnerabilities Protection)",
                "Symantec Endpoint Security": "⚠️ (via SEPM add-on)",
                "Trellix": "⚠️ (via vulnerability management)",
                "ESET Protect": "⚠️",
                "CrowdStrike": "⚠️",
                "Kaspersky": "⚠️",
                "Microsoft Defender aka MDE Support": "⚠️",
                "Norton": "❌",
                "SentinelOne": "⚠",
                "Sophos": "❌",
                "TrendMicro": "⚠️"
            },
            {
                "Feature / Capability": "Encryption (BitLocker and FileVault management)",
                "Description": "Manages disk encryption on Windows/Mac endpoints",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "⚠️",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "❌",
                "McAfee ENS + ePO": "⚠️ (ePO Encryption)",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "⚠️ (PGP Encryption add-on)",
                "Trellix": "⚠️ (DLP with encryption)",
                "ESET Protect": "⚠️",
                "CrowdStrike": "⚠️",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "⚠️",
                "Norton": "❌",
                "SentinelOne": "⚠",
                "Sophos": "⚠️",
                "TrendMicro": "⚠️"
            },
            {
                "Feature / Capability": "Application Control & Privilege Management",
                "Description": "Controls application access and user privileges",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "⚠️",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "⚠️",
                "McAfee ENS + ePO": "⚠️ (ePO App Control)",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "⚠️ (via policy management)",
                "ESET Protect": "⚠️",
                "CrowdStrike": "⚠️",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "⚠️",
                "Norton": "❌",
                "SentinelOne": "⚠",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Peripheral Device Control",
                "Description": "Controls USB and external device usage",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "⚠️",
                "McAfee ENS + ePO": "⚠️ (add-on)",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "⚠️ (DLP device control)",
                "ESET Protect": "✅",
                "CrowdStrike": "✅",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Endpoint Data Leakage Prevention (DLP)",
                "Description": "Prevents unauthorized transfer of sensitive data",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "⚠️",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "❌",
                "McAfee ENS + ePO": "⚠️ (McAfee DLP)",
                "Palo Alto Cortex XDR": "❌",
                "Symantec Endpoint Security": "⚠️ (DLP add-on)",
                "Trellix": "✅ (Trellix DLP)",
                "ESET Protect": "⚠️",
                "CrowdStrike": "⚠️",
                "Kaspersky": "⚠️",
                "Microsoft Defender aka MDE Support": "⚠️",
                "Norton": "❌",
                "SentinelOne": "⚠",
                "Sophos": "✅",
                "TrendMicro": "⚠️"
            },
            {
                "Feature / Capability": "Browser Security",
                "Description": "Protects from browser-based threats and phishing",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "✅",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "❌",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "⚠️",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "✅",
                "SentinelOne": "⚠",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "OS Deployment",
                "Description": "Centralized OS deployment and imaging",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "❌",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "❌",
                "McAfee ENS + ePO": "❌",
                "Palo Alto Cortex XDR": "❌",
                "Symantec Endpoint Security": "❌",
                "Trellix": "❌",
                "ESET Protect": "⚠️",
                "CrowdStrike": "❌",
                "Kaspersky": "⚠️",
                "Microsoft Defender aka MDE Support": "❌",
                "Norton": "❌",
                "SentinelOne": "❌",
                "Sophos": "⚠️",
                "TrendMicro": "❌"
            },
            {
                "Feature / Capability": "Mobile Device Management (MDM)",
                "Description": "Managing iOS and Android devices",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "⚠️",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "❌",
                "McAfee ENS + ePO": "❌",
                "Palo Alto Cortex XDR": "❌",
                "Symantec Endpoint Security": "⚠️ (limited mobile support)",
                "Trellix": "⚠️ (limited mobile support)",
                "ESET Protect": "✅",
                "CrowdStrike": "⚠️",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "⚠️",
                "Norton": "❌",
                "SentinelOne": "⚠",
                "Sophos": "⚠️",
                "TrendMicro": "⚠️"
            },
            {
                "Feature / Capability": "Remote Control (built-in)",
                "Description": "Native secure remote desktop for IT support",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "⚠️",
                "Bitdefender AV / GravityZone": "❌",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "❌",
                "McAfee ENS + ePO": "⚠️ (ePO Remote Support)",
                "Palo Alto Cortex XDR": "❌",
                "Symantec Endpoint Security": "❌",
                "Trellix": "⚠️ (via security management)",
                "ESET Protect": "⚠️",
                "CrowdStrike": "✅",
                "Kaspersky": "⚠️",
                "Microsoft Defender aka MDE Support": "❌",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "❌",
                "TrendMicro": "❌"
            },
            {
                "Feature / Capability": "Configuration Management",
                "Description": "Policy configuration and enforcement",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "⚠️",
                "McAfee ENS + ePO": "⚠️ (ePO Policy Mgmt)",
                "Palo Alto Cortex XDR": "❌",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "⚠️",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "⚠",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Software Distribution",
                "Description": "Automated app/software deployment",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "❌",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "❌",
                "McAfee ENS + ePO": "✅ (via ePO)",
                "Palo Alto Cortex XDR": "❌",
                "Symantec Endpoint Security": "⚠️ (limited via SEPM)",
                "Trellix": "⚠️ (limited capabilities)",
                "ESET Protect": "✅",
                "CrowdStrike": "❌",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "❌",
                "Norton": "❌",
                "SentinelOne": "❌",
                "Sophos": "⚠️",
                "TrendMicro": "❌"
            },
            {
                "Feature / Capability": "Hardware & Software Inventory",
                "Description": "Asset management of hardware and software",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "⚠️",
                "CyclancePROTECT": "❌",
                "Datto EDR": "⚠️",
                "Malwarebytes (ThreatDown)": "⚠️",
                "McAfee ENS + ePO": "✅ (via ePO)",
                "Palo Alto Cortex XDR": "❌",
                "Symantec Endpoint Security": "⚠️ (basic inventory)",
                "Trellix": "⚠️ (asset visibility)",
                "ESET Protect": "✅",
                "CrowdStrike": "⚠️",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "❌",
                "SentinelOne": "⚠",
                "Sophos": "⚠️",
                "TrendMicro": "⚠️"
            },
            {
                "Feature / Capability": "Patch Management",
                "Description": "Automated patch deployment and compliance reporting",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "⚠️",
                "Bitdefender AV / GravityZone": "⚠️",
                "CyclancePROTECT": "❌",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "⚠️",
                "McAfee ENS + ePO": "⚠️ (ePO Patch Mgmt)",
                "Palo Alto Cortex XDR": "❌",
                "Symantec Endpoint Security": "⚠️ (limited via SEMP)",
                "Trellix": "⚠️ (vulnerability management)",
                "ESET Protect": "⚠️",
                "CrowdStrike": "❌",
                "Kaspersky": "⚠️",
                "Microsoft Defender aka MDE Support": "⚠️",
                "Norton": "❌",
                "SentinelOne": "⚠",
                "Sophos": "❌",
                "TrendMicro": "⚠️"
            },
            {
                "Feature / Capability": "Compliance & Audit Reports",
                "Description": "Customizable compliance and usage reports",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "⚠️",
                "CyclancePROTECT": "❌",
                "Datto EDR": "✅",
                "Malwarebytes (ThreatDown)": "⚠️",
                "McAfee ENS + ePO": "✅ (via ePO)",
                "Palo Alto Cortex XDR": "✅",
                "Symantec Endpoint Security": "✅",
                "Trellix": "⚠️ (reporting capabilities)",
                "ESET Protect": "✅",
                "CrowdStrike": "⚠️",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "✅",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            },
            {
                "Feature / Capability": "Power Management",
                "Description": "Automated energy management on endpoints",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "❌",
                "Bitdefender AV / GravityZone": "❌",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "❌",
                "McAfee ENS + ePO": "❌",
                "Palo Alto Cortex XDR": "❌",
                "Symantec Endpoint Security": "✅",
                "Trellix": "❌",
                "ESET Protect": "❌",
                "CrowdStrike": "❌",
                "Kaspersky": "❌",
                "Microsoft Defender aka MDE Support": "❌",
                "Norton": "❌",
                "SentinelOne": "❌",
                "Sophos": "❌",
                "TrendMicro": "❌"
            },
            {
                "Feature / Capability": "Pricing Security - Endpoint protection license (per device/year)",
                "Description": "Total pricing for all security features (per device/year)",
                "Endpoint Central Malware Protection": "$ 22 ",
                "Avast AV": "$56.99/$60.41",
                "Bitdefender AV / GravityZone": "$77.69–$99.99 + add-ons*",
                "CyclancePROTECT": "$45→$26 (volume)",
                "Datto EDR": "$35.88",
                "Malwarebytes (ThreatDown)": "$69–$119†",
                "McAfee ENS + ePO": "~$39.99‡",
                "Palo Alto Cortex XDR": "$81",
                "Symantec Endpoint Security": "$37–$55",
                "Trellix": "$35–$50",
                "ESET Protect": "$211/device/year",
                "CrowdStrike": "$99-$185 per endpoint annually",
                "Kaspersky": "$45-$99/device/year",
                "Microsoft Defender aka MDE Support": "$62.40/user/year",
                "Norton": "$14.99-$24.99",
                "SentinelOne": "$69.99-$209.99",
                "Sophos": "$108",
                "TrendMicro": "$25-$45 per device/year"
            },
            {
                "Feature / Capability": "Pricing Management - Additional endpoint management modules/licenses (patch, encryption, etc.)",
                "Description": "Total pricing for all management features (per device/year)",
                "Endpoint Central Malware Protection": "$ 22 ",
                "Avast AV": "~$49.99 (RC)",
                "Bitdefender AV / GravityZone": "$10–$30+ /device/yr",
                "CyclancePROTECT": "--",
                "Datto EDR": "$35.88",
                "Malwarebytes (ThreatDown)": "$10+ (Patch Mgmt)†",
                "McAfee ENS + ePO": "~$20+ (ePO modules)",
                "Palo Alto Cortex XDR": "--",
                "Symantec Endpoint Security": "$15–$25+ (SEPM add-ons)",
                "Trellix": "Bundled/Add-on ($10-$20)",
                "ESET Protect": "$76/device/year",
                "CrowdStrike": "DLP: ~$50-100/endpoint, Mobile: ~$25-50/endpoint",
                "Kaspersky": "$30-$55/device/year",
                "Microsoft Defender aka MDE Support": "$168/user/year",
                "Norton": "",
                "SentinelOne": "$20-50 per device/year",
                "Sophos": "$143",
                "TrendMicro": "$19-$34 per device/year"
            },
            {
                "Feature / Capability": "Available as a self-hosted version",
                "Description": "If the product on-premises or on cloud",
                "Endpoint Central Malware Protection": "✅",
                "Avast AV": "✅",
                "Bitdefender AV / GravityZone": "✅",
                "CyclancePROTECT": "❌",
                "Datto EDR": "❌",
                "Malwarebytes (ThreatDown)": "❌",
                "McAfee ENS + ePO": "✅",
                "Palo Alto Cortex XDR": "❌",
                "Symantec Endpoint Security": "✅",
                "Trellix": "✅",
                "ESET Protect": "✅",
                "CrowdStrike": "❌",
                "Kaspersky": "✅",
                "Microsoft Defender aka MDE Support": "❌",
                "Norton": "❌",
                "SentinelOne": "✅",
                "Sophos": "✅",
                "TrendMicro": "✅"
            }
]
# ===================================

if not dataset:
    st.error("No data provided.")
    st.stop()

feature_col = "Feature / Capability"
desc_col = "Description"
me_col = "Endpoint Central Malware Protection"
competitors = [k for k in dataset[0] if k not in [feature_col, desc_col, me_col]]

st.title("Endpoint Central Malware Protection | Tool Comparator")

# Select competitor
selected_vendor = st.selectbox("Compare ManageEngine with:", competitors)

def is_yes(value):
    if not value:
        return False
    return str(value).strip() in ['✅', '✔', '✓', 'Yes', 'TRUE', '1']

# --- TL;DR Section: show 3–5 points (randomly) ---
all_advantages = [
    f"**{row[feature_col]}**: {row.get(desc_col,'')}"
    for row in dataset
    if is_yes(row.get(me_col)) and not is_yes(row.get(selected_vendor))
]

if all_advantages:
    show_count = min(len(all_advantages), random.choice([3, 4, 5]))
    shown_advantages = random.sample(all_advantages, show_count)
else:
    shown_advantages = []

st.header("TL;DR — How ManageEngine is better")
if shown_advantages:
    for adv in shown_advantages:
        st.markdown(f"- {adv}")
else:
    st.write("No clear advantages found.")

# --- Table: Show full view, no scrolling ---
table = [
    {
        feature_col: row.get(feature_col, ""),
        desc_col: row.get(desc_col, ""),
        "ManageEngine": row.get(me_col, ""),
        selected_vendor: row.get(selected_vendor, "")
    }
    for row in dataset
]

df = pd.DataFrame(table)
row_height = 35  # pixels per row, adjust as needed
full_height = max(600, row_height * (len(df) + 3))

st.header("Comparison Table")
st.dataframe(df, height=full_height, use_container_width=True)

# ---- (Optional) Download HTML button ----
def generate_html():
    html = f"<h1>ManageEngine vs {selected_vendor}</h1>\n"
    html += "<h2>TL;DR — How ManageEngine is better</h2>\n<ul>"
    for adv in shown_advantages:
        html += f"<li>{adv}</li>\n"
    html += "</ul>\n"
    html += "<h2>Comparison Table</h2>\n<table border='1' cellpadding='5' cellspacing='0'>"
    html += f"<tr><th>Feature / Capability</th><th>Description</th><th>ManageEngine</th><th>{selected_vendor}</th></tr>"
    for row in table:
        html += f"<tr><td>{row[feature_col]}</td><td>{row[desc_col]}</td><td>{row['ManageEngine']}</td><td>{row[selected_vendor]}</td></tr>"
    html += "</table>"
    return html

def get_download_link(text, filename):
    b64 = base64.b64encode(text.encode()).decode()
    return f'<a download="{filename}" href="data:text/html;base64,{b64}">Download Comparison Report</a>'

st.markdown(get_download_link(generate_html(), f"ManageEngine_vs_{selected_vendor}.html"), unsafe_allow_html=True)
